version: "3"
services:
    mysql:
        image: mysql:latest
        container_name: mysql_node
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
            # MYSQL_DATABASE: node_database
            MYSQL_USER: node
            MYSQL_PASSWORD: password
            TZ: "Asia/Tokyo"
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
        volumes:
            - "/Users/shinoharamichihiro/data:/var/lib/mysql"
            - "/Users/shinoharamichihiro/conf:/etc/mysql/conf.d"
            - "/Users/shinoharamichihiro/initdb:/docker-entrypoint-initdb.d"
        ports:
            - 3307:3306
